// src/constants/templates.ts

import { TemplateCategory } from '../types';

export const TEMPLATE_LIBRARY: TemplateCategory[] = [
  {
    id: 'real-estate',
    name: 'Real Estate',
    description: 'Templates for property listings, showings, and client communication',
    icon: 'home',
    templates: [
      {
        id: 're-listing',
        title: 'Property Listing',
        content: `🏡 NEW LISTING ALERT!\n\nProperty: [Address]\nPrice: $[Price]\nBeds: [#] | Baths: [#]\nSq Ft: [Size]\n\n✨ Features:\n• [Feature 1]\n• [Feature 2]\n• [Feature 3]\n\n📅 Open House: [Date & Time]\n\nInterested? Contact me to schedule a private showing!`,
        category: 'sales',
        industry: 'real-estate',
        tags: ['listing', 'property', 'sales'],
      },
      {
        id: 're-showing',
        title: 'Showing Confirmation',
        content: `Hi [Name],\n\nConfirming your property showing for:\n\n📍 Address: [Property Address]\n📅 Date: [Date]\n⏰ Time: [Time]\n\nI'll meet you at the property. Please bring a valid ID.\n\nLooking forward to showing you this amazing home!`,
        category: 'follow-ups',
        industry: 'real-estate',
        tags: ['showing', 'appointment', 'confirmation'],
      },
      {
        id: 're-offer',
        title: 'Offer Received',
        content: `Great news! We've received an offer on your property at [Address].\n\nOffer Details:\n💰 Offer Price: $[Amount]\n📝 Contingencies: [Details]\n⏰ Close Date: [Date]\n\nLet's discuss the details and our next steps. When can we talk?`,
        category: 'sales',
        industry: 'real-estate',
        tags: ['offer', 'negotiation'],
      },
      {
        id: 're-followup',
        title: 'Post-Showing Follow-Up',
        content: `Hi [Name],\n\nThank you for viewing [Property Address] today! I hope you loved it as much as I thought you would.\n\nWhat were your thoughts? Any questions about the property or neighborhood?\n\nI'm here to help with next steps whenever you're ready!`,
        category: 'follow-ups',
        industry: 'real-estate',
        tags: ['follow-up', 'showing'],
      },
    ],
  },
  {
    id: 'sales',
    name: 'Sales & Business',
    description: 'Professional sales templates for outreach, proposals, and closing',
    icon: 'briefcase',
    templates: [
      {
        id: 'sales-intro',
        title: 'Cold Outreach',
        content: `Hi [Name],\n\nI noticed [something specific about their business/situation].\n\nI help companies like yours [specific benefit]. We recently helped [similar company] achieve [specific result].\n\nWould you be open to a 15-minute call this week to explore how we could help you achieve similar results?\n\nBest regards,\n[Your Name]`,
        category: 'prospecting',
        industry: 'sales',
        tags: ['cold-email', 'outreach', 'prospecting'],
      },
      {
        id: 'sales-proposal',
        title: 'Proposal Follow-Up',
        content: `Hi [Name],\n\nFollowing up on the proposal I sent on [Date].\n\nKey highlights:\n✓ [Benefit 1]\n✓ [Benefit 2]\n✓ [Benefit 3]\n\nInvestment: $[Amount]\nTimeline: [Duration]\n\nDo you have any questions? I'd love to discuss how we can get started.`,
        category: 'follow-ups',
        industry: 'sales',
        tags: ['proposal', 'follow-up'],
      },
      {
        id: 'sales-objection-price',
        title: 'Price Objection Handler',
        content: `I understand budget is an important consideration.\n\nLet me break down the ROI:\n\n💰 Investment: $[Amount]\n📈 Expected Return: $[Amount] ([X]x ROI)\n⏱️ Payback Period: [Timeframe]\n\nMost clients see the investment pay for itself within [timeframe]. Plus, we offer [payment plans/guarantee].\n\nWould a customized payment plan make this work for your budget?`,
        category: 'objections',
        industry: 'sales',
        tags: ['objection', 'pricing', 'negotiation'],
      },
      {
        id: 'sales-closing',
        title: 'Closing Question',
        content: `Based on our conversations, it seems like [Product/Service] would be a great fit for [specific goal].\n\nHere's what happens next:\n1️⃣ Sign agreement\n2️⃣ Onboarding call within 24-48h\n3️⃣ See results by [timeframe]\n\nAre you ready to move forward? I can get everything set up today.`,
        category: 'closing',
        industry: 'sales',
        tags: ['closing', 'deal'],
      },
      {
        id: 'sales-referral',
        title: 'Referral Request',
        content: `Hi [Name],\n\nI'm so glad we've been able to help you with [result achieved]!\n\nDo you know anyone else who might benefit from [service]? I'd love to help them achieve similar results.\n\nFor every referral, you'll receive [incentive].\n\nThanks for considering!`,
        category: 'follow-ups',
        industry: 'sales',
        tags: ['referral', 'networking'],
      },
    ],
  },
  {
    id: 'support',
    name: 'Customer Support',
    description: 'Professional support responses for common customer inquiries',
    icon: 'message-circle',
    templates: [
      {
        id: 'support-greeting',
        title: 'Initial Response',
        content: `Hi [Name],\n\nThank you for reaching out! I'm here to help.\n\nI understand you're experiencing [issue]. Let me look into this for you right away.\n\nI'll get back to you within [timeframe] with a solution.\n\nIn the meantime, have you tried [quick fix]?`,
        category: 'sales',
        industry: 'support',
        tags: ['support', 'greeting', 'acknowledgment'],
      },
      {
        id: 'support-resolved',
        title: 'Issue Resolved',
        content: `Great news, [Name]!\n\nYour issue has been resolved. Here's what we did:\n\n✓ [Action 1]\n✓ [Action 2]\n✓ [Action 3]\n\nPlease test it out and let me know if everything works as expected.\n\nIs there anything else I can help you with today?`,
        category: 'sales',
        industry: 'support',
        tags: ['resolution', 'follow-up'],
      },
      {
        id: 'support-escalation',
        title: 'Escalation Notice',
        content: `Hi [Name],\n\nI've escalated your case to our senior support team for faster resolution.\n\nTicket #: [Number]\nPriority: High\nExpected Resolution: [Timeframe]\n\nYou'll hear from [Name/Team] within [timeframe].\n\nWe appreciate your patience!`,
        category: 'follow-ups',
        industry: 'support',
        tags: ['escalation', 'priority'],
      },
      {
        id: 'support-faq',
        title: 'FAQ Response',
        content: `Great question!\n\nHere's how [feature/process] works:\n\n1️⃣ [Step 1]\n2️⃣ [Step 2]\n3️⃣ [Step 3]\n\n💡 Pro Tip: [Helpful tip]\n\nYou can find more info in our knowledge base: [Link]\n\nDoes this answer your question?`,
        category: 'sales',
        industry: 'support',
        tags: ['faq', 'tutorial'],
      },
      {
        id: 'support-refund',
        title: 'Refund Request',
        content: `Hi [Name],\n\nI'm sorry to hear that [Product/Service] didn't meet your expectations.\n\nI've processed your refund request:\n\n💰 Amount: $[Amount]\n⏱️ Processing Time: 5-7 business days\n🏦 Method: Original payment method\n\nWould you mind sharing why it didn't work out? Your feedback helps us improve.\n\nThank you for giving us a try!`,
        category: 'sales',
        industry: 'support',
        tags: ['refund', 'cancellation'],
      },
    ],
  },
  {
    id: 'hr',
    name: 'Human Resources',
    description: 'HR templates for recruiting, onboarding, and employee communication',
    icon: 'users',
    templates: [
      {
        id: 'hr-job-posting',
        title: 'Job Posting',
        content: `🚀 We're Hiring: [Job Title]\n\n📍 Location: [Location/Remote]\n💼 Type: [Full-time/Part-time/Contract]\n💰 Salary: $[Range]\n\nWe're looking for:\n✓ [Requirement 1]\n✓ [Requirement 2]\n✓ [Requirement 3]\n\n🎁 Benefits:\n• [Benefit 1]\n• [Benefit 2]\n• [Benefit 3]\n\nInterested? Apply here: [Link]`,
        category: 'sales',
        industry: 'hr',
        tags: ['recruiting', 'job-posting'],
      },
      {
        id: 'hr-interview',
        title: 'Interview Invitation',
        content: `Hi [Name],\n\nThank you for applying for the [Position] role at [Company]!\n\nWe'd love to schedule an interview:\n\n📅 Date Options:\n• [Option 1]\n• [Option 2]\n• [Option 3]\n\n⏱️ Duration: [X] minutes\n📍 Format: [In-person/Video/Phone]\n\nPlease confirm which time works best for you.\n\nLooking forward to speaking with you!`,
        category: 'follow-ups',
        industry: 'hr',
        tags: ['interview', 'scheduling'],
      },
      {
        id: 'hr-offer',
        title: 'Job Offer',
        content: `Congratulations, [Name]!\n\nWe're excited to offer you the position of [Job Title] at [Company]!\n\nOffer Details:\n💰 Salary: $[Amount]/year\n📅 Start Date: [Date]\n🏖️ PTO: [Days] days/year\n🎁 Benefits: [Brief list]\n\nPlease review the attached offer letter and let us know your decision by [Date].\n\nWelcome to the team!`,
        category: 'sales',
        industry: 'hr',
        tags: ['offer', 'hiring'],
      },
      {
        id: 'hr-onboarding',
        title: 'Onboarding Welcome',
        content: `Welcome to [Company], [Name]! 🎉\n\nYour First Day Details:\n📅 Date: [Date]\n⏰ Time: [Time]\n📍 Location: [Address/Link]\n\nWhat to Bring:\n✓ ID for paperwork\n✓ Bank details for payroll\n✓ [Other items]\n\nYour onboarding buddy: [Name] ([Email])\n\nExcited to have you on the team!`,
        category: 'welcome',
        industry: 'hr',
        tags: ['onboarding', 'welcome'],
      },
      {
        id: 'hr-rejection',
        title: 'Candidate Rejection',
        content: `Hi [Name],\n\nThank you for your interest in the [Position] role and for taking the time to interview with us.\n\nAfter careful consideration, we've decided to move forward with other candidates whose experience more closely matches our current needs.\n\nWe were impressed by [specific positive], and we encourage you to apply for future openings that match your skills.\n\nThank you again, and best of luck in your job search!`,
        category: 'follow-ups',
        industry: 'hr',
        tags: ['rejection', 'recruiting'],
      },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Healthcare templates for appointments, reminders, and patient communication',
    icon: 'heart-pulse',
    templates: [
      {
        id: 'health-appointment',
        title: 'Appointment Confirmation',
        content: `Hi [Patient Name],\n\nAppointment Confirmed ✓\n\n👨‍⚕️ Provider: Dr. [Name]\n📅 Date: [Date]\n⏰ Time: [Time]\n📍 Location: [Address]\n\nPlease arrive 15 minutes early to complete any necessary paperwork.\n\nNeed to reschedule? Reply or call [Phone].`,
        category: 'welcome',
        industry: 'healthcare',
        tags: ['appointment', 'confirmation'],
      },
      {
        id: 'health-reminder',
        title: 'Appointment Reminder',
        content: `⏰ Appointment Reminder\n\nHi [Patient Name],\n\nThis is a reminder of your upcoming appointment:\n\n📅 Tomorrow at [Time]\n📍 [Clinic Name]\n👨‍⚕️ Dr. [Name]\n\nWhat to bring:\n• Insurance card\n• Photo ID\n• Current medications list\n\nSee you soon!`,
        category: 'follow-ups',
        industry: 'healthcare',
        tags: ['reminder', 'appointment'],
      },
      {
        id: 'health-results',
        title: 'Test Results Available',
        content: `Hi [Patient Name],\n\nYour test results from [Date] are now available.\n\nPlease call our office at [Phone] or log into the patient portal to review them.\n\nIf you have any questions, we're here to help.\n\nThank you,\n[Clinic Name]`,
        category: 'follow-ups',
        industry: 'healthcare',
        tags: ['results', 'follow-up'],
      },
      {
        id: 'health-prescription',
        title: 'Prescription Ready',
        content: `Hi [Patient Name],\n\nYour prescription for [Medication] is ready for pickup at:\n\n🏥 [Pharmacy Name]\n📍 [Address]\n⏰ Hours: [Hours]\n\nPickup within [X] days.\n\nQuestions? Call [Phone]\n\nFeel better soon!`,
        category: 'follow-ups',
        industry: 'healthcare',
        tags: ['prescription', 'pharmacy'],
      },
      {
        id: 'health-followup',
        title: 'Follow-Up Care',
        content: `Hi [Patient Name],\n\nHow are you feeling after your visit on [Date]?\n\nPlease remember to:\n✓ [Instruction 1]\n✓ [Instruction 2]\n✓ [Instruction 3]\n\nNext appointment: [Date] (if applicable)\n\nContact us if you experience [warning signs].\n\nWishing you a speedy recovery!`,
        category: 'follow-ups',
        industry: 'healthcare',
        tags: ['follow-up', 'care'],
      },
    ],
  },
];
